version: "3"
services:
  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app-container
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana-oss:8.4.3
    depends_on:
      - library-app
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - library-app